/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package recipefinder;

public class App {
    public String getGreeting() {
        Connect.connect();
        // InsertData.insertData();
        return "RecipeFinder is running!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
